### ISSUE TITLE
document handling endpoint

### ISSUE THREAD

**Issue by maland** [DeepLcom/deepl-rb#1]
are there any plans to include the document translation to this gem?

as when trying to directly send data to the endpoint i always receive: {"message":"Invalid file data."}

**Comment by JanEbbing** [comment]
Yes, we are planning to add all features to this library soon, it's not yet an official DeepL library, sorry.

**Comment by JanEbbing** [comment]
This has now been released in 3.0.0, if you want to use it over the weekend please keep this issue in mind https://github.com/DeepLcom/deepl-rb/issues/2 . I will fix this on Monday and release 3.0.1
